#!/bin/sh

echo "finding files......"

find . -name "*.h" -o -name "*.c" -o -name "*.cpp" -o -name "*.cc" -o -name "*.cxx" -o -name "*.java" -o -name "*.s" -o -name "*.S" > cscope.files

echo "initint db......"

cscope -bkq -i cscope.files

ctags -R

echo "DONE"
